config/routes.rb
Rails.application.routes.draw do
  root 'messages#index'
  post 'messages/poke_cow' => 'messages#poke_cow', as: 'poke_cow'
  post 'messages/massage_cow' => 'messages#massage_cow', as: 'massage_cow'
  get  'messages/broadcasting' => 'messages#broadcasting'

end

app/models/message.rb
class Message < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  include ActionController::Live
  # Mime::Type.register "text/event-stream", :stream

  def index
    @messages = Message.all.order created_at: :desc
  end

  # POST
  def poke_cow
    # CowsayJob.set(wait_until: (Time.now + 1.minute)).perform_later
    CowsayJob.perform_later
    # Rails.queue.push reviews_search
    # Rails.queue.push(CowsayJob.new(user))
    redirect_to root_path, notice: 'Cow at work...'
  end  

  # POST
  def massage_cow
    MassageCowJob.perform_later #each_minute: 0.2
    redirect_to root_path, notice: 'Beginning to massage the cow...'
  end

  def broadcasting
    response.headers['Content-Type'] = 'text/event-stream'
    
    start_time = Time.zone.now    
    # TODO ???
    loop do
      Message.uncached do          
        Message.where("created_at > ?", start_time).each do |m|
          # response.stream.write "event: message\n"          
          response.stream.write %Q(data: #{m.to_json}\n\n)
          start_time = m.created_at
        end    
      end  
      sleep 2
    end
    
    # sse = SSE.new(response.stream, retry: 300, event: "message")
    # sse.write({ name: 'John'}, id: 10)
    # sse.write({ name: 'John'}, id: 10, event: "other-event")
    # sse.write({ name: 'John'}, id: 10, event: "other-event", retry: 500)
    # ensure
    # sse.close
    # render nothing: true
    rescue IOError
    ensure
      response.stream.close
      # TODO
      # Rake::Task['jobs:clear'].invoke
      `bundle exec rake jobs:clear` # Delayed::Job.count      
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/views/layouts/application.html.haml
!!!
%html
  %head
    %title Cowsay
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    = csrf_meta_tags
  
  %body
    = notice if notice
    = alert if alert
    = yield

app/views/messages/_message.html.haml
%p.message
  %code= message.body

app/views/messages/index.html.haml
%h1 Recent messages from the Cow
= link_to 'Poke the cow', poke_cow_path, method: :post
%br
= link_to 'Massage the cow', massage_cow_path, method: :post
%p.messages
  = render @messages